package com.hpb.bc.mapper;

import com.hpb.bc.entity.AddressErcHolder;
import com.hpb.bc.entity.ContractErcStandardInfo;
import com.hpb.bc.example.AddressErcHolderExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AddressErcHolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_erc_holder
     *
     * @mbg.generated
     */
    long countByExample(AddressErcHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_erc_holder
     *
     * @mbg.generated
     */
    int deleteByExample(AddressErcHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_erc_holder
     *
     * @mbg.generated
     */
    int insert(AddressErcHolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_erc_holder
     *
     * @mbg.generated
     */
    int insertSelective(AddressErcHolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_erc_holder
     *
     * @mbg.generated
     */
    List<AddressErcHolder> selectByExample(AddressErcHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_erc_holder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AddressErcHolder record, @Param("example") AddressErcHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_erc_holder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AddressErcHolder record, @Param("example") AddressErcHolderExample example);


    int selectHoldersCountByContractAddress(@Param("contractAddress") String contractAddress);

    List<ContractErcStandardInfo> selectHoldersCountByContractAddressList(@Param("list") List<String> contractAddressList);
}