/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.mapper;

import com.hpb.bc.entity.ApiKey;
import com.hpb.bc.example.ApiKeyExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ApiKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    long countByExample(ApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    int deleteByExample(ApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    int insert(ApiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    int insertSelective(ApiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    List<ApiKey> selectByExample(ApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    ApiKey selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiKey record, @Param("example") ApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiKey record, @Param("example") ApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiKey record);

    /**
     * select by apiKey
     */
    ApiKey selectApiKeyByKey(@Param("apiKey") String apiKey);
}