/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.mapper;

import com.hpb.bc.entity.BlockMaxSize;
import com.hpb.bc.example.BlockMaxSizeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BlockMaxSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    long countByExample(BlockMaxSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    int deleteByExample(BlockMaxSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    int insert(BlockMaxSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    int insertSelective(BlockMaxSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    List<BlockMaxSize> selectByExample(BlockMaxSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    BlockMaxSize selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlockMaxSize record, @Param("example") BlockMaxSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlockMaxSize record, @Param("example") BlockMaxSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlockMaxSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_max_size
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlockMaxSize record);
}