/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.mapper;

import com.hpb.bc.entity.CommonDictionary;
import com.hpb.bc.example.CommonDictionaryExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CommonDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    long countByExample(CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int deleteByExample(CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int insert(CommonDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int insertSelective(CommonDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    List<CommonDictionary> selectByExample(CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    CommonDictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommonDictionary record, @Param("example") CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommonDictionary record, @Param("example") CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommonDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommonDictionary record);
}