package com.hpb.bc.mapper;

import com.hpb.bc.entity.CommonDictionary;
import com.hpb.bc.example.CommonDictionaryExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CommonDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    long countByExample(CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int deleteByExample(CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int insert(CommonDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int insertSelective(CommonDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    List<CommonDictionary> selectByExample(CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    CommonDictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommonDictionary record, @Param("example") CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommonDictionary record, @Param("example") CommonDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommonDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommonDictionary record);
}