/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.mapper;

import com.hpb.bc.entity.ContractErcProfileSummary;
import com.hpb.bc.example.ContractErcProfileSummaryExample;
import java.util.List;

import com.hpb.bc.model.ContractErcProfileSummaryModel;
import org.apache.ibatis.annotations.Param;

public interface ContractErcProfileSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    long countByExample(ContractErcProfileSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int deleteByExample(ContractErcProfileSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int insert(ContractErcProfileSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int insertSelective(ContractErcProfileSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    List<ContractErcProfileSummary> selectByExampleWithBLOBs(ContractErcProfileSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    List<ContractErcProfileSummary> selectByExample(ContractErcProfileSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    ContractErcProfileSummary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContractErcProfileSummary record, @Param("example") ContractErcProfileSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ContractErcProfileSummary record, @Param("example") ContractErcProfileSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContractErcProfileSummary record, @Param("example") ContractErcProfileSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContractErcProfileSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ContractErcProfileSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContractErcProfileSummary record);



    void saveMoreInfo(ContractErcProfileSummaryModel.ContractErcProfileSummaryInner formContent);

    int updateMoreInfo(ContractErcProfileSummaryModel.ContractErcProfileSummaryInner formContent);

    ContractErcProfileSummary selectMoreInfoByAddress(@Param("contactAddress") String contactAddress);

}