/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.mapper;

import com.hpb.bc.entity.ContractEventInfo;
import com.hpb.bc.example.ContractEventInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractEventInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    long countByExample(ContractEventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int deleteByExample(ContractEventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int insert(ContractEventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int insertSelective(ContractEventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    List<ContractEventInfo> selectByExampleWithBLOBs(ContractEventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    List<ContractEventInfo> selectByExample(ContractEventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    ContractEventInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContractEventInfo record, @Param("example") ContractEventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ContractEventInfo record, @Param("example") ContractEventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContractEventInfo record, @Param("example") ContractEventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContractEventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ContractEventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_event_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContractEventInfo record);
}