package com.hpb.bc.mapper;

import com.hpb.bc.entity.HpbCampaignPeriodVoteResult;
import com.hpb.bc.example.HpbCampaignPeriodVoteResultExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface HpbCampaignPeriodVoteResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_campaign_period_vote_result
     *
     * @mbg.generated
     */
    long countByExample(HpbCampaignPeriodVoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_campaign_period_vote_result
     *
     * @mbg.generated
     */
    int deleteByExample(HpbCampaignPeriodVoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_campaign_period_vote_result
     *
     * @mbg.generated
     */
    int insert(HpbCampaignPeriodVoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_campaign_period_vote_result
     *
     * @mbg.generated
     */
    int insertSelective(HpbCampaignPeriodVoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_campaign_period_vote_result
     *
     * @mbg.generated
     */
    List<HpbCampaignPeriodVoteResult> selectByExample(HpbCampaignPeriodVoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_campaign_period_vote_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpbCampaignPeriodVoteResult record, @Param("example") HpbCampaignPeriodVoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_campaign_period_vote_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpbCampaignPeriodVoteResult record, @Param("example") HpbCampaignPeriodVoteResultExample example);
}