/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.mapper;

import com.hpb.bc.entity.HpbMarketPrice;
import com.hpb.bc.example.HpbMarketPriceExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface HpbMarketPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    long countByExample(HpbMarketPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    int deleteByExample(HpbMarketPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer priceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    int insert(HpbMarketPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    int insertSelective(HpbMarketPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    List<HpbMarketPrice> selectByExample(HpbMarketPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    HpbMarketPrice selectByPrimaryKey(Integer priceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpbMarketPrice record, @Param("example") HpbMarketPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpbMarketPrice record, @Param("example") HpbMarketPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpbMarketPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpbMarketPrice record);

    List<HpbMarketPrice> selectEchartData();

    HpbMarketPrice selectByDate(Date date);
}