package com.hpb.bc.mapper;

import com.hpb.bc.entity.HpbNodeRewardRecord;
import com.hpb.bc.example.HpbNodeRewardRecordExample;

import java.math.BigDecimal;
import java.util.List;

import com.hpb.bc.vo.NodeDailyRewardVo;
import org.apache.ibatis.annotations.Param;

public interface HpbNodeRewardRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    long countByExample(HpbNodeRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    int deleteByExample(HpbNodeRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    int insert(HpbNodeRewardRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    int insertSelective(HpbNodeRewardRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    List<HpbNodeRewardRecord> selectByExample(HpbNodeRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpbNodeRewardRecord record, @Param("example") HpbNodeRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpbNodeRewardRecord record, @Param("example") HpbNodeRewardRecordExample example);

    BigDecimal selectSumVoteRewardByAddressAndStartBlockNumberAndEndBlockNumber(@Param("address") String address,@Param("startBlockTimestamp")  long startBlockTimestamp,@Param("endBlockTimestamp")  long endBlockTimestamp);

    List<HpbNodeRewardRecord> selectNodeRewardList(@Param("address") String address,@Param("startBlockTimestamp")  long startBlockTimestamp,@Param("endBlockTimestamp") long endBlockTimestamp);

    List<NodeDailyRewardVo> selectNodeDailyRewardList(@Param("address") String address,@Param("startBlockTimestamp")  long startBlockTimestamp,@Param("endBlockTimestamp") long endBlockTimestamp);

    List<NodeDailyRewardVo> selectNodeMonthRewardList(@Param("address") String address,@Param("startBlockTimestamp")  long startBlockTimestamp,@Param("endBlockTimestamp") long endBlockTimestamp);



    List<NodeDailyRewardVo> selectNodeDailyRewardAssignedList(@Param("queryDateTime") String queryDateTime);


    List<NodeDailyRewardVo> selectNodeMonthRewardAssignedList(@Param("queryDateTime") String queryDateTime);






}