package com.hpb.bc.mapper;

import com.hpb.bc.entity.TxInternalRecord;
import com.hpb.bc.example.TxInternalRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxInternalRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_internal_record
     *
     * @mbg.generated
     */
    long countByExample(TxInternalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_internal_record
     *
     * @mbg.generated
     */
    int deleteByExample(TxInternalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_internal_record
     *
     * @mbg.generated
     */
    int insert(TxInternalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_internal_record
     *
     * @mbg.generated
     */
    int insertSelective(TxInternalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_internal_record
     *
     * @mbg.generated
     */
    List<TxInternalRecord> selectByExample(TxInternalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_internal_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TxInternalRecord record, @Param("example") TxInternalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_internal_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TxInternalRecord record, @Param("example") TxInternalRecordExample example);

    List<TxInternalRecord> selectTxInternalRecordListByBlockHash(@Param("blockHash") String blockHash);

    List<TxInternalRecord> selectTxInternalRecordListByBlockNumber(@Param("blockNumber") String blockNumber);

    List<TxInternalRecord> selectTxInternalRecordListByFromAddress(@Param("fromAddress") String contractAddress);

    List<TxInternalRecord> selectTxInternalRecordListByToAddress(@Param("toAddress") String contractAddress);

    List<TxInternalRecord> selectTxInternalRecordListByReferedAddress(@Param("referedAddress") String contractAddress);

    List<TxInternalRecord> selectTxInternalRecordListByTxHash(@Param("txHash") String txHash);

}