/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.mapper;

import com.hpb.bc.entity.ContractErcStandardInfo;
import com.hpb.bc.entity.TxTransferRecord;
import com.hpb.bc.example.TxTransferRecordExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TxTransferRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_record
     *
     * @mbg.generated
     */
    long countByExample(TxTransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_record
     *
     * @mbg.generated
     */
    int deleteByExample(TxTransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_record
     *
     * @mbg.generated
     */
    int insert(TxTransferRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_record
     *
     * @mbg.generated
     */
    int insertSelective(TxTransferRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_record
     *
     * @mbg.generated
     */
    List<TxTransferRecord> selectByExample(TxTransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TxTransferRecord record, @Param("example") TxTransferRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_transfer_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TxTransferRecord record, @Param("example") TxTransferRecordExample example);

    List<TxTransferRecord> selectTxTransferRecordListByContractAddress(@Param("contractAddress") String contractAddress);

    int selectTransferCountByAddress(@Param("contractAddress") String contractAddress);

    List<TxTransferRecord> selectTxTransferRecordListByBlockHash(@Param("blockHash") String blockHash);

    List<TxTransferRecord> selectTxTransferRecordListByBlockNumber(@Param("blockNumber") String blockNumber);

    List<TxTransferRecord> selectTxTransferRecordListByFromAddress(@Param("fromAddress") String contractAddress);

    List<TxTransferRecord> selectTxTransferRecordListByToAddress(@Param("toAddress") String contractAddress);

    List<TxTransferRecord> selectTxTransferRecordListByReferedAddress(@Param("referedAddress") String contractAddress);

    List<TxTransferRecord> selectTxTransferRecordListByReferedAddressAndContractAddress(@Param("referedAddress") String referedAddress, @Param("contractAddress") String contractAddress);

    List<TxTransferRecord> selectHrc721Storage(@Param("address") String address);

    int  selectTotalTransferNumByContractAddress(@Param("contractAddress") String contractAddress);

    int selectTotalTransferNumByContractAddressHolderAddress(@Param("contractAddress") String contractAddress,@Param("holderAddress") String holderAddress);

    ContractErcStandardInfo selectTotalTransferNumByContractAddressList(@Param("contractAddress") String contractAddress);
}