/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HpbNodeRewardRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public HpbNodeRewardRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNodeAddressIsNull() {
            addCriterion("node_address is null");
            return (Criteria) this;
        }

        public Criteria andNodeAddressIsNotNull() {
            addCriterion("node_address is not null");
            return (Criteria) this;
        }

        public Criteria andNodeAddressEqualTo(String value) {
            addCriterion("node_address =", value, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressNotEqualTo(String value) {
            addCriterion("node_address <>", value, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressGreaterThan(String value) {
            addCriterion("node_address >", value, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressGreaterThanOrEqualTo(String value) {
            addCriterion("node_address >=", value, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressLessThan(String value) {
            addCriterion("node_address <", value, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressLessThanOrEqualTo(String value) {
            addCriterion("node_address <=", value, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressLike(String value) {
            addCriterion("node_address like", value, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressNotLike(String value) {
            addCriterion("node_address not like", value, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressIn(List<String> values) {
            addCriterion("node_address in", values, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressNotIn(List<String> values) {
            addCriterion("node_address not in", values, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressBetween(String value1, String value2) {
            addCriterion("node_address between", value1, value2, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeAddressNotBetween(String value1, String value2) {
            addCriterion("node_address not between", value1, value2, "nodeAddress");
            return (Criteria) this;
        }

        public Criteria andNodeNameIsNull() {
            addCriterion("node_name is null");
            return (Criteria) this;
        }

        public Criteria andNodeNameIsNotNull() {
            addCriterion("node_name is not null");
            return (Criteria) this;
        }

        public Criteria andNodeNameEqualTo(String value) {
            addCriterion("node_name =", value, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameNotEqualTo(String value) {
            addCriterion("node_name <>", value, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameGreaterThan(String value) {
            addCriterion("node_name >", value, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameGreaterThanOrEqualTo(String value) {
            addCriterion("node_name >=", value, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameLessThan(String value) {
            addCriterion("node_name <", value, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameLessThanOrEqualTo(String value) {
            addCriterion("node_name <=", value, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameLike(String value) {
            addCriterion("node_name like", value, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameNotLike(String value) {
            addCriterion("node_name not like", value, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameIn(List<String> values) {
            addCriterion("node_name in", values, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameNotIn(List<String> values) {
            addCriterion("node_name not in", values, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameBetween(String value1, String value2) {
            addCriterion("node_name between", value1, value2, "nodeName");
            return (Criteria) this;
        }

        public Criteria andNodeNameNotBetween(String value1, String value2) {
            addCriterion("node_name not between", value1, value2, "nodeName");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountIsNull() {
            addCriterion("total_vote_amount is null");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountIsNotNull() {
            addCriterion("total_vote_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountEqualTo(String value) {
            addCriterion("total_vote_amount =", value, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountNotEqualTo(String value) {
            addCriterion("total_vote_amount <>", value, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountGreaterThan(String value) {
            addCriterion("total_vote_amount >", value, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountGreaterThanOrEqualTo(String value) {
            addCriterion("total_vote_amount >=", value, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountLessThan(String value) {
            addCriterion("total_vote_amount <", value, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountLessThanOrEqualTo(String value) {
            addCriterion("total_vote_amount <=", value, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountLike(String value) {
            addCriterion("total_vote_amount like", value, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountNotLike(String value) {
            addCriterion("total_vote_amount not like", value, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountIn(List<String> values) {
            addCriterion("total_vote_amount in", values, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountNotIn(List<String> values) {
            addCriterion("total_vote_amount not in", values, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountBetween(String value1, String value2) {
            addCriterion("total_vote_amount between", value1, value2, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andTotalVoteAmountNotBetween(String value1, String value2) {
            addCriterion("total_vote_amount not between", value1, value2, "totalVoteAmount");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(BigDecimal value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(BigDecimal value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(BigDecimal value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(BigDecimal value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<BigDecimal> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<BigDecimal> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andNodeTypeIsNull() {
            addCriterion("node_type is null");
            return (Criteria) this;
        }

        public Criteria andNodeTypeIsNotNull() {
            addCriterion("node_type is not null");
            return (Criteria) this;
        }

        public Criteria andNodeTypeEqualTo(String value) {
            addCriterion("node_type =", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeNotEqualTo(String value) {
            addCriterion("node_type <>", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeGreaterThan(String value) {
            addCriterion("node_type >", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("node_type >=", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeLessThan(String value) {
            addCriterion("node_type <", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeLessThanOrEqualTo(String value) {
            addCriterion("node_type <=", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeLike(String value) {
            addCriterion("node_type like", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeNotLike(String value) {
            addCriterion("node_type not like", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeIn(List<String> values) {
            addCriterion("node_type in", values, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeNotIn(List<String> values) {
            addCriterion("node_type not in", values, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeBetween(String value1, String value2) {
            addCriterion("node_type between", value1, value2, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeNotBetween(String value1, String value2) {
            addCriterion("node_type not between", value1, value2, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountIsNull() {
            addCriterion("node_mint_reward_amount is null");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountIsNotNull() {
            addCriterion("node_mint_reward_amount is not null");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountEqualTo(BigDecimal value) {
            addCriterion("node_mint_reward_amount =", value, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountNotEqualTo(BigDecimal value) {
            addCriterion("node_mint_reward_amount <>", value, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountGreaterThan(BigDecimal value) {
            addCriterion("node_mint_reward_amount >", value, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("node_mint_reward_amount >=", value, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountLessThan(BigDecimal value) {
            addCriterion("node_mint_reward_amount <", value, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("node_mint_reward_amount <=", value, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountIn(List<BigDecimal> values) {
            addCriterion("node_mint_reward_amount in", values, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountNotIn(List<BigDecimal> values) {
            addCriterion("node_mint_reward_amount not in", values, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("node_mint_reward_amount between", value1, value2, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeMintRewardAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("node_mint_reward_amount not between", value1, value2, "nodeMintRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountIsNull() {
            addCriterion("node_vote_reward_amount is null");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountIsNotNull() {
            addCriterion("node_vote_reward_amount is not null");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountEqualTo(BigDecimal value) {
            addCriterion("node_vote_reward_amount =", value, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountNotEqualTo(BigDecimal value) {
            addCriterion("node_vote_reward_amount <>", value, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountGreaterThan(BigDecimal value) {
            addCriterion("node_vote_reward_amount >", value, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("node_vote_reward_amount >=", value, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountLessThan(BigDecimal value) {
            addCriterion("node_vote_reward_amount <", value, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("node_vote_reward_amount <=", value, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountIn(List<BigDecimal> values) {
            addCriterion("node_vote_reward_amount in", values, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountNotIn(List<BigDecimal> values) {
            addCriterion("node_vote_reward_amount not in", values, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("node_vote_reward_amount between", value1, value2, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeVoteRewardAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("node_vote_reward_amount not between", value1, value2, "nodeVoteRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountIsNull() {
            addCriterion("node_total_reward_amount is null");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountIsNotNull() {
            addCriterion("node_total_reward_amount is not null");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountEqualTo(BigDecimal value) {
            addCriterion("node_total_reward_amount =", value, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountNotEqualTo(BigDecimal value) {
            addCriterion("node_total_reward_amount <>", value, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountGreaterThan(BigDecimal value) {
            addCriterion("node_total_reward_amount >", value, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("node_total_reward_amount >=", value, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountLessThan(BigDecimal value) {
            addCriterion("node_total_reward_amount <", value, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("node_total_reward_amount <=", value, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountIn(List<BigDecimal> values) {
            addCriterion("node_total_reward_amount in", values, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountNotIn(List<BigDecimal> values) {
            addCriterion("node_total_reward_amount not in", values, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("node_total_reward_amount between", value1, value2, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andNodeTotalRewardAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("node_total_reward_amount not between", value1, value2, "nodeTotalRewardAmount");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateIsNull() {
            addCriterion("reward_vote_percent_rate is null");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateIsNotNull() {
            addCriterion("reward_vote_percent_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateEqualTo(BigDecimal value) {
            addCriterion("reward_vote_percent_rate =", value, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateNotEqualTo(BigDecimal value) {
            addCriterion("reward_vote_percent_rate <>", value, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateGreaterThan(BigDecimal value) {
            addCriterion("reward_vote_percent_rate >", value, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reward_vote_percent_rate >=", value, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateLessThan(BigDecimal value) {
            addCriterion("reward_vote_percent_rate <", value, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reward_vote_percent_rate <=", value, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateIn(List<BigDecimal> values) {
            addCriterion("reward_vote_percent_rate in", values, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateNotIn(List<BigDecimal> values) {
            addCriterion("reward_vote_percent_rate not in", values, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reward_vote_percent_rate between", value1, value2, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andRewardVotePercentRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reward_vote_percent_rate not between", value1, value2, "rewardVotePercentRate");
            return (Criteria) this;
        }

        public Criteria andBlockNumberIsNull() {
            addCriterion("block_number is null");
            return (Criteria) this;
        }

        public Criteria andBlockNumberIsNotNull() {
            addCriterion("block_number is not null");
            return (Criteria) this;
        }

        public Criteria andBlockNumberEqualTo(Long value) {
            addCriterion("block_number =", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberNotEqualTo(Long value) {
            addCriterion("block_number <>", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberGreaterThan(Long value) {
            addCriterion("block_number >", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("block_number >=", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberLessThan(Long value) {
            addCriterion("block_number <", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberLessThanOrEqualTo(Long value) {
            addCriterion("block_number <=", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberIn(List<Long> values) {
            addCriterion("block_number in", values, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberNotIn(List<Long> values) {
            addCriterion("block_number not in", values, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberBetween(Long value1, Long value2) {
            addCriterion("block_number between", value1, value2, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberNotBetween(Long value1, Long value2) {
            addCriterion("block_number not between", value1, value2, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockHashIsNull() {
            addCriterion("block_hash is null");
            return (Criteria) this;
        }

        public Criteria andBlockHashIsNotNull() {
            addCriterion("block_hash is not null");
            return (Criteria) this;
        }

        public Criteria andBlockHashEqualTo(String value) {
            addCriterion("block_hash =", value, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashNotEqualTo(String value) {
            addCriterion("block_hash <>", value, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashGreaterThan(String value) {
            addCriterion("block_hash >", value, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashGreaterThanOrEqualTo(String value) {
            addCriterion("block_hash >=", value, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashLessThan(String value) {
            addCriterion("block_hash <", value, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashLessThanOrEqualTo(String value) {
            addCriterion("block_hash <=", value, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashLike(String value) {
            addCriterion("block_hash like", value, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashNotLike(String value) {
            addCriterion("block_hash not like", value, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashIn(List<String> values) {
            addCriterion("block_hash in", values, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashNotIn(List<String> values) {
            addCriterion("block_hash not in", values, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashBetween(String value1, String value2) {
            addCriterion("block_hash between", value1, value2, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockHashNotBetween(String value1, String value2) {
            addCriterion("block_hash not between", value1, value2, "blockHash");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampIsNull() {
            addCriterion("block_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampIsNotNull() {
            addCriterion("block_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampEqualTo(Long value) {
            addCriterion("block_timestamp =", value, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampNotEqualTo(Long value) {
            addCriterion("block_timestamp <>", value, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampGreaterThan(Long value) {
            addCriterion("block_timestamp >", value, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampGreaterThanOrEqualTo(Long value) {
            addCriterion("block_timestamp >=", value, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampLessThan(Long value) {
            addCriterion("block_timestamp <", value, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampLessThanOrEqualTo(Long value) {
            addCriterion("block_timestamp <=", value, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampIn(List<Long> values) {
            addCriterion("block_timestamp in", values, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampNotIn(List<Long> values) {
            addCriterion("block_timestamp not in", values, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampBetween(Long value1, Long value2) {
            addCriterion("block_timestamp between", value1, value2, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andBlockTimestampNotBetween(Long value1, Long value2) {
            addCriterion("block_timestamp not between", value1, value2, "blockTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("create_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("create_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("create_timestamp =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("create_timestamp <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("create_timestamp >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("create_timestamp >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("create_timestamp <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("create_timestamp <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("create_timestamp in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("create_timestamp not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("create_timestamp between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("create_timestamp not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("update_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("update_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("update_timestamp =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("update_timestamp <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("update_timestamp >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("update_timestamp >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("update_timestamp <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("update_timestamp <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("update_timestamp in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("update_timestamp not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("update_timestamp between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("update_timestamp not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_node_reward_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}