/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.entity;

import java.math.BigInteger;
import java.util.Date;

public class Addrs extends BaseEntity {
    private static final long serialVersionUID = 7132993445788839288L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrs.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrs.number
     *
     * @mbg.generated
     */
    private Long number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrs.start_block
     *
     * @mbg.generated
     */
    private Long startBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrs.lastest_block
     *
     * @mbg.generated
     */
    private Long lastestBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrs.from_count
     *
     * @mbg.generated
     */
    private Long fromCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrs.to_count
     *
     * @mbg.generated
     */
    private Long toCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrs.account_type
     *
     * @mbg.generated
     */
    private Integer accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrs.balance
     *
     * @mbg.generated
     */
    private BigInteger balance;

    private String balanceStr;

    private String percentRate;
    /**
     * 资产排名
     */
    private String assetRankingOrder;

    private Date createTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrs.address
     *
     * @return the value of addrs.address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrs.address
     *
     * @param address the value for addrs.address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrs.number
     *
     * @return the value of addrs.number
     * @mbg.generated
     */
    public Long getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrs.number
     *
     * @param number the value for addrs.number
     * @mbg.generated
     */
    public void setNumber(Long number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrs.start_block
     *
     * @return the value of addrs.start_block
     * @mbg.generated
     */
    public Long getStartBlock() {
        return startBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrs.start_block
     *
     * @param startBlock the value for addrs.start_block
     * @mbg.generated
     */
    public void setStartBlock(Long startBlock) {
        this.startBlock = startBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrs.lastest_block
     *
     * @return the value of addrs.lastest_block
     * @mbg.generated
     */
    public Long getLastestBlock() {
        return lastestBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrs.lastest_block
     *
     * @param lastestBlock the value for addrs.lastest_block
     * @mbg.generated
     */
    public void setLastestBlock(Long lastestBlock) {
        this.lastestBlock = lastestBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrs.from_count
     *
     * @return the value of addrs.from_count
     * @mbg.generated
     */
    public Long getFromCount() {
        return fromCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrs.from_count
     *
     * @param fromCount the value for addrs.from_count
     * @mbg.generated
     */
    public void setFromCount(Long fromCount) {
        this.fromCount = fromCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrs.to_count
     *
     * @return the value of addrs.to_count
     * @mbg.generated
     */
    public Long getToCount() {
        return toCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrs.to_count
     *
     * @param toCount the value for addrs.to_count
     * @mbg.generated
     */
    public void setToCount(Long toCount) {
        this.toCount = toCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrs.account_type
     *
     * @return the value of addrs.account_type
     * @mbg.generated
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrs.account_type
     *
     * @param accountType the value for addrs.account_type
     * @mbg.generated
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrs.balance
     *
     * @return the value of addrs.balance
     * @mbg.generated
     */
    public BigInteger getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrs.balance
     *
     * @param balance the value for addrs.balance
     * @mbg.generated
     */
    public void setBalance(BigInteger balance) {
        this.balance = balance;
    }

    public String getBalanceStr() {
        return balanceStr;
    }

    public void setBalanceStr(String balanceStr) {
        this.balanceStr = balanceStr;
    }

    public String getPercentRate() {
        return percentRate;
    }

    public void setPercentRate(String percentRate) {
        this.percentRate = percentRate;
    }

    public String getAssetRankingOrder() {
        return assetRankingOrder;
    }

    public void setAssetRankingOrder(String assetRankingOrder) {
        this.assetRankingOrder = assetRankingOrder;
    }


    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addrs
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Addrs other = (Addrs) that;
        return (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
                && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
                && (this.getStartBlock() == null ? other.getStartBlock() == null : this.getStartBlock().equals(other.getStartBlock()))
                && (this.getLastestBlock() == null ? other.getLastestBlock() == null : this.getLastestBlock().equals(other.getLastestBlock()))
                && (this.getFromCount() == null ? other.getFromCount() == null : this.getFromCount().equals(other.getFromCount()))
                && (this.getToCount() == null ? other.getToCount() == null : this.getToCount().equals(other.getToCount()))
                && (this.getAccountType() == null ? other.getAccountType() == null : this.getAccountType().equals(other.getAccountType()))
                && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()))
                && (this.getCreateTimestamp() == null ? other.getCreateTimestamp() == null : this.getCreateTimestamp().equals(other.getCreateTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addrs
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getStartBlock() == null) ? 0 : getStartBlock().hashCode());
        result = prime * result + ((getLastestBlock() == null) ? 0 : getLastestBlock().hashCode());
        result = prime * result + ((getFromCount() == null) ? 0 : getFromCount().hashCode());
        result = prime * result + ((getToCount() == null) ? 0 : getToCount().hashCode());
        result = prime * result + ((getAccountType() == null) ? 0 : getAccountType().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getCreateTimestamp() == null) ? 0 : getCreateTimestamp().hashCode());
        return result;
    }
}