/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.entity;

import java.util.Date;

public class ContractErcProfileSummaryApprove extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.token_symbol_image_url
     *
     * @mbg.generated
     */
    private String tokenSymbolImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.token_name
     *
     * @mbg.generated
     */
    private String tokenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.contract_address
     *
     * @mbg.generated
     */
    private String contractAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.contract_type
     *
     * @mbg.generated
     */
    private String contractType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.official_site
     *
     * @mbg.generated
     */
    private String officialSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.telegram
     *
     * @mbg.generated
     */
    private String telegram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.approve_status
     *
     * @mbg.generated
     */
    private String approveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.profile_en
     *
     * @mbg.generated
     */
    private String profileEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.profile_zh
     *
     * @mbg.generated
     */
    private String profileZh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.facebook
     *
     * @mbg.generated
     */
    private String facebook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.twitter
     *
     * @mbg.generated
     */
    private String twitter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.weibo
     *
     * @mbg.generated
     */
    private String weibo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_erc_profile_summary_approve.github
     *
     * @mbg.generated
     */
    private String github;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.id
     *
     * @return the value of contract_erc_profile_summary_approve.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.id
     *
     * @param id the value for contract_erc_profile_summary_approve.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.token_symbol_image_url
     *
     * @return the value of contract_erc_profile_summary_approve.token_symbol_image_url
     *
     * @mbg.generated
     */
    public String getTokenSymbolImageUrl() {
        return tokenSymbolImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.token_symbol_image_url
     *
     * @param tokenSymbolImageUrl the value for contract_erc_profile_summary_approve.token_symbol_image_url
     *
     * @mbg.generated
     */
    public void setTokenSymbolImageUrl(String tokenSymbolImageUrl) {
        this.tokenSymbolImageUrl = tokenSymbolImageUrl == null ? null : tokenSymbolImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.token_name
     *
     * @return the value of contract_erc_profile_summary_approve.token_name
     *
     * @mbg.generated
     */
    public String getTokenName() {
        return tokenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.token_name
     *
     * @param tokenName the value for contract_erc_profile_summary_approve.token_name
     *
     * @mbg.generated
     */
    public void setTokenName(String tokenName) {
        this.tokenName = tokenName == null ? null : tokenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.contract_address
     *
     * @return the value of contract_erc_profile_summary_approve.contract_address
     *
     * @mbg.generated
     */
    public String getContractAddress() {
        return contractAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.contract_address
     *
     * @param contractAddress the value for contract_erc_profile_summary_approve.contract_address
     *
     * @mbg.generated
     */
    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress == null ? null : contractAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.contract_type
     *
     * @return the value of contract_erc_profile_summary_approve.contract_type
     *
     * @mbg.generated
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.contract_type
     *
     * @param contractType the value for contract_erc_profile_summary_approve.contract_type
     *
     * @mbg.generated
     */
    public void setContractType(String contractType) {
        this.contractType = contractType == null ? null : contractType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.official_site
     *
     * @return the value of contract_erc_profile_summary_approve.official_site
     *
     * @mbg.generated
     */
    public String getOfficialSite() {
        return officialSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.official_site
     *
     * @param officialSite the value for contract_erc_profile_summary_approve.official_site
     *
     * @mbg.generated
     */
    public void setOfficialSite(String officialSite) {
        this.officialSite = officialSite == null ? null : officialSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.email
     *
     * @return the value of contract_erc_profile_summary_approve.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.email
     *
     * @param email the value for contract_erc_profile_summary_approve.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.telegram
     *
     * @return the value of contract_erc_profile_summary_approve.telegram
     *
     * @mbg.generated
     */
    public String getTelegram() {
        return telegram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.telegram
     *
     * @param telegram the value for contract_erc_profile_summary_approve.telegram
     *
     * @mbg.generated
     */
    public void setTelegram(String telegram) {
        this.telegram = telegram == null ? null : telegram.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.approve_status
     *
     * @return the value of contract_erc_profile_summary_approve.approve_status
     *
     * @mbg.generated
     */
    public String getApproveStatus() {
        return approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.approve_status
     *
     * @param approveStatus the value for contract_erc_profile_summary_approve.approve_status
     *
     * @mbg.generated
     */
    public void setApproveStatus(String approveStatus) {
        this.approveStatus = approveStatus == null ? null : approveStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.create_time
     *
     * @return the value of contract_erc_profile_summary_approve.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.create_time
     *
     * @param createTime the value for contract_erc_profile_summary_approve.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.update_time
     *
     * @return the value of contract_erc_profile_summary_approve.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.update_time
     *
     * @param updateTime the value for contract_erc_profile_summary_approve.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.profile_en
     *
     * @return the value of contract_erc_profile_summary_approve.profile_en
     *
     * @mbg.generated
     */
    public String getProfileEn() {
        return profileEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.profile_en
     *
     * @param profileEn the value for contract_erc_profile_summary_approve.profile_en
     *
     * @mbg.generated
     */
    public void setProfileEn(String profileEn) {
        this.profileEn = profileEn == null ? null : profileEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.profile_zh
     *
     * @return the value of contract_erc_profile_summary_approve.profile_zh
     *
     * @mbg.generated
     */
    public String getProfileZh() {
        return profileZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.profile_zh
     *
     * @param profileZh the value for contract_erc_profile_summary_approve.profile_zh
     *
     * @mbg.generated
     */
    public void setProfileZh(String profileZh) {
        this.profileZh = profileZh == null ? null : profileZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.facebook
     *
     * @return the value of contract_erc_profile_summary_approve.facebook
     *
     * @mbg.generated
     */
    public String getFacebook() {
        return facebook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.facebook
     *
     * @param facebook the value for contract_erc_profile_summary_approve.facebook
     *
     * @mbg.generated
     */
    public void setFacebook(String facebook) {
        this.facebook = facebook == null ? null : facebook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.twitter
     *
     * @return the value of contract_erc_profile_summary_approve.twitter
     *
     * @mbg.generated
     */
    public String getTwitter() {
        return twitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.twitter
     *
     * @param twitter the value for contract_erc_profile_summary_approve.twitter
     *
     * @mbg.generated
     */
    public void setTwitter(String twitter) {
        this.twitter = twitter == null ? null : twitter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.weibo
     *
     * @return the value of contract_erc_profile_summary_approve.weibo
     *
     * @mbg.generated
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.weibo
     *
     * @param weibo the value for contract_erc_profile_summary_approve.weibo
     *
     * @mbg.generated
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_erc_profile_summary_approve.github
     *
     * @return the value of contract_erc_profile_summary_approve.github
     *
     * @mbg.generated
     */
    public String getGithub() {
        return github;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_erc_profile_summary_approve.github
     *
     * @param github the value for contract_erc_profile_summary_approve.github
     *
     * @mbg.generated
     */
    public void setGithub(String github) {
        this.github = github == null ? null : github.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary_approve
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ContractErcProfileSummaryApprove other = (ContractErcProfileSummaryApprove) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTokenSymbolImageUrl() == null ? other.getTokenSymbolImageUrl() == null : this.getTokenSymbolImageUrl().equals(other.getTokenSymbolImageUrl()))
            && (this.getTokenName() == null ? other.getTokenName() == null : this.getTokenName().equals(other.getTokenName()))
            && (this.getContractAddress() == null ? other.getContractAddress() == null : this.getContractAddress().equals(other.getContractAddress()))
            && (this.getContractType() == null ? other.getContractType() == null : this.getContractType().equals(other.getContractType()))
            && (this.getOfficialSite() == null ? other.getOfficialSite() == null : this.getOfficialSite().equals(other.getOfficialSite()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getTelegram() == null ? other.getTelegram() == null : this.getTelegram().equals(other.getTelegram()))
            && (this.getApproveStatus() == null ? other.getApproveStatus() == null : this.getApproveStatus().equals(other.getApproveStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getProfileEn() == null ? other.getProfileEn() == null : this.getProfileEn().equals(other.getProfileEn()))
            && (this.getProfileZh() == null ? other.getProfileZh() == null : this.getProfileZh().equals(other.getProfileZh()))
            && (this.getFacebook() == null ? other.getFacebook() == null : this.getFacebook().equals(other.getFacebook()))
            && (this.getTwitter() == null ? other.getTwitter() == null : this.getTwitter().equals(other.getTwitter()))
            && (this.getWeibo() == null ? other.getWeibo() == null : this.getWeibo().equals(other.getWeibo()))
            && (this.getGithub() == null ? other.getGithub() == null : this.getGithub().equals(other.getGithub()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_profile_summary_approve
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTokenSymbolImageUrl() == null) ? 0 : getTokenSymbolImageUrl().hashCode());
        result = prime * result + ((getTokenName() == null) ? 0 : getTokenName().hashCode());
        result = prime * result + ((getContractAddress() == null) ? 0 : getContractAddress().hashCode());
        result = prime * result + ((getContractType() == null) ? 0 : getContractType().hashCode());
        result = prime * result + ((getOfficialSite() == null) ? 0 : getOfficialSite().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getTelegram() == null) ? 0 : getTelegram().hashCode());
        result = prime * result + ((getApproveStatus() == null) ? 0 : getApproveStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getProfileEn() == null) ? 0 : getProfileEn().hashCode());
        result = prime * result + ((getProfileZh() == null) ? 0 : getProfileZh().hashCode());
        result = prime * result + ((getFacebook() == null) ? 0 : getFacebook().hashCode());
        result = prime * result + ((getTwitter() == null) ? 0 : getTwitter().hashCode());
        result = prime * result + ((getWeibo() == null) ? 0 : getWeibo().hashCode());
        result = prime * result + ((getGithub() == null) ? 0 : getGithub().hashCode());
        return result;
    }
}