/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.entity;

import java.math.BigDecimal;
import java.util.Date;

public class HpbMarketPrice extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.price_id
     *
     * @mbg.generated
     */
    private Integer priceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.price_usd
     *
     * @mbg.generated
     */
    private BigDecimal priceUsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.usd_rate
     *
     * @mbg.generated
     */
    private BigDecimal usdRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.price_time
     *
     * @mbg.generated
     */
    private Date priceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.market_cap
     *
     * @mbg.generated
     */
    private String marketCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.volume_24h
     *
     * @mbg.generated
     */
    private String volume24h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_market_price.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.price_id
     *
     * @return the value of hpb_market_price.price_id
     * @mbg.generated
     */
    public Integer getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.price_id
     *
     * @param priceId the value for hpb_market_price.price_id
     * @mbg.generated
     */
    public void setPriceId(Integer priceId) {
        this.priceId = priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.price
     *
     * @return the value of hpb_market_price.price
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.price
     *
     * @param price the value for hpb_market_price.price
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.price_usd
     *
     * @return the value of hpb_market_price.price_usd
     * @mbg.generated
     */
    public BigDecimal getPriceUsd() {
        return priceUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.price_usd
     *
     * @param priceUsd the value for hpb_market_price.price_usd
     * @mbg.generated
     */
    public void setPriceUsd(BigDecimal priceUsd) {
        this.priceUsd = priceUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.usd_rate
     *
     * @return the value of hpb_market_price.usd_rate
     * @mbg.generated
     */
    public BigDecimal getUsdRate() {
        return usdRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.usd_rate
     *
     * @param usdRate the value for hpb_market_price.usd_rate
     * @mbg.generated
     */
    public void setUsdRate(BigDecimal usdRate) {
        this.usdRate = usdRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.price_time
     *
     * @return the value of hpb_market_price.price_time
     * @mbg.generated
     */
    public Date getPriceTime() {
        return priceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.price_time
     *
     * @param priceTime the value for hpb_market_price.price_time
     * @mbg.generated
     */
    public void setPriceTime(Date priceTime) {
        this.priceTime = priceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.market_cap
     *
     * @return the value of hpb_market_price.market_cap
     * @mbg.generated
     */
    public String getMarketCap() {
        return marketCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.market_cap
     *
     * @param marketCap the value for hpb_market_price.market_cap
     * @mbg.generated
     */
    public void setMarketCap(String marketCap) {
        this.marketCap = marketCap == null ? null : marketCap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.volume_24h
     *
     * @return the value of hpb_market_price.volume_24h
     * @mbg.generated
     */
    public String getVolume24h() {
        return volume24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.volume_24h
     *
     * @param volume24h the value for hpb_market_price.volume_24h
     * @mbg.generated
     */
    public void setVolume24h(String volume24h) {
        this.volume24h = volume24h == null ? null : volume24h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.create_time
     *
     * @return the value of hpb_market_price.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.create_time
     *
     * @param createTime the value for hpb_market_price.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.update_time
     *
     * @return the value of hpb_market_price.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.update_time
     *
     * @param updateTime the value for hpb_market_price.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_market_price.remark
     *
     * @return the value of hpb_market_price.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_market_price.remark
     *
     * @param remark the value for hpb_market_price.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HpbMarketPrice other = (HpbMarketPrice) that;
        return (this.getPriceId() == null ? other.getPriceId() == null : this.getPriceId().equals(other.getPriceId()))
                && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
                && (this.getPriceUsd() == null ? other.getPriceUsd() == null : this.getPriceUsd().equals(other.getPriceUsd()))
                && (this.getUsdRate() == null ? other.getUsdRate() == null : this.getUsdRate().equals(other.getUsdRate()))
                && (this.getPriceTime() == null ? other.getPriceTime() == null : this.getPriceTime().equals(other.getPriceTime()))
                && (this.getMarketCap() == null ? other.getMarketCap() == null : this.getMarketCap().equals(other.getMarketCap()))
                && (this.getVolume24h() == null ? other.getVolume24h() == null : this.getVolume24h().equals(other.getVolume24h()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_market_price
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPriceId() == null) ? 0 : getPriceId().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getPriceUsd() == null) ? 0 : getPriceUsd().hashCode());
        result = prime * result + ((getUsdRate() == null) ? 0 : getUsdRate().hashCode());
        result = prime * result + ((getPriceTime() == null) ? 0 : getPriceTime().hashCode());
        result = prime * result + ((getMarketCap() == null) ? 0 : getMarketCap().hashCode());
        result = prime * result + ((getVolume24h() == null) ? 0 : getVolume24h().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}