package com.hpb.bc.entity;

import java.util.Date;

public class HpbNodeVoteRecordDetail extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.candidate_address
     *
     * @mbg.generated
     */
    private String candidateAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.candidate_name
     *
     * @mbg.generated
     */
    private String candidateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.vote_round
     *
     * @mbg.generated
     */
    private Integer voteRound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.vote_stage
     *
     * @mbg.generated
     */
    private Integer voteStage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.voter_address
     *
     * @mbg.generated
     */
    private String voterAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.snap_block_number
     *
     * @mbg.generated
     */
    private Long snapBlockNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.snap_block_timestamp
     *
     * @mbg.generated
     */
    private Long snapBlockTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.vote_total_amount
     *
     * @mbg.generated
     */
    private String voteTotalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.create_timestamp
     *
     * @mbg.generated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpb_node_vote_record_detail.update_timestamp
     *
     * @mbg.generated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.id
     *
     * @return the value of hpb_node_vote_record_detail.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.id
     *
     * @param id the value for hpb_node_vote_record_detail.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.candidate_address
     *
     * @return the value of hpb_node_vote_record_detail.candidate_address
     * @mbg.generated
     */
    public String getCandidateAddress() {
        return candidateAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.candidate_address
     *
     * @param candidateAddress the value for hpb_node_vote_record_detail.candidate_address
     * @mbg.generated
     */
    public void setCandidateAddress(String candidateAddress) {
        this.candidateAddress = candidateAddress == null ? null : candidateAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.candidate_name
     *
     * @return the value of hpb_node_vote_record_detail.candidate_name
     * @mbg.generated
     */
    public String getCandidateName() {
        return candidateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.candidate_name
     *
     * @param candidateName the value for hpb_node_vote_record_detail.candidate_name
     * @mbg.generated
     */
    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName == null ? null : candidateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.vote_round
     *
     * @return the value of hpb_node_vote_record_detail.vote_round
     * @mbg.generated
     */
    public Integer getVoteRound() {
        return voteRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.vote_round
     *
     * @param voteRound the value for hpb_node_vote_record_detail.vote_round
     * @mbg.generated
     */
    public void setVoteRound(Integer voteRound) {
        this.voteRound = voteRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.vote_stage
     *
     * @return the value of hpb_node_vote_record_detail.vote_stage
     * @mbg.generated
     */
    public Integer getVoteStage() {
        return voteStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.vote_stage
     *
     * @param voteStage the value for hpb_node_vote_record_detail.vote_stage
     * @mbg.generated
     */
    public void setVoteStage(Integer voteStage) {
        this.voteStage = voteStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.voter_address
     *
     * @return the value of hpb_node_vote_record_detail.voter_address
     * @mbg.generated
     */
    public String getVoterAddress() {
        return voterAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.voter_address
     *
     * @param voterAddress the value for hpb_node_vote_record_detail.voter_address
     * @mbg.generated
     */
    public void setVoterAddress(String voterAddress) {
        this.voterAddress = voterAddress == null ? null : voterAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.snap_block_number
     *
     * @return the value of hpb_node_vote_record_detail.snap_block_number
     * @mbg.generated
     */
    public Long getSnapBlockNumber() {
        return snapBlockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.snap_block_number
     *
     * @param snapBlockNumber the value for hpb_node_vote_record_detail.snap_block_number
     * @mbg.generated
     */
    public void setSnapBlockNumber(Long snapBlockNumber) {
        this.snapBlockNumber = snapBlockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.snap_block_timestamp
     *
     * @return the value of hpb_node_vote_record_detail.snap_block_timestamp
     * @mbg.generated
     */
    public Long getSnapBlockTimestamp() {
        return snapBlockTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.snap_block_timestamp
     *
     * @param snapBlockTimestamp the value for hpb_node_vote_record_detail.snap_block_timestamp
     * @mbg.generated
     */
    public void setSnapBlockTimestamp(Long snapBlockTimestamp) {
        this.snapBlockTimestamp = snapBlockTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.vote_total_amount
     *
     * @return the value of hpb_node_vote_record_detail.vote_total_amount
     * @mbg.generated
     */
    public String getVoteTotalAmount() {
        return voteTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.vote_total_amount
     *
     * @param voteTotalAmount the value for hpb_node_vote_record_detail.vote_total_amount
     * @mbg.generated
     */
    public void setVoteTotalAmount(String voteTotalAmount) {
        this.voteTotalAmount = voteTotalAmount == null ? null : voteTotalAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.create_timestamp
     *
     * @return the value of hpb_node_vote_record_detail.create_timestamp
     * @mbg.generated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.create_timestamp
     *
     * @param createTimestamp the value for hpb_node_vote_record_detail.create_timestamp
     * @mbg.generated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpb_node_vote_record_detail.update_timestamp
     *
     * @return the value of hpb_node_vote_record_detail.update_timestamp
     * @mbg.generated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpb_node_vote_record_detail.update_timestamp
     *
     * @param updateTimestamp the value for hpb_node_vote_record_detail.update_timestamp
     * @mbg.generated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_vote_record_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HpbNodeVoteRecordDetail other = (HpbNodeVoteRecordDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getCandidateAddress() == null ? other.getCandidateAddress() == null : this.getCandidateAddress().equals(other.getCandidateAddress()))
                && (this.getCandidateName() == null ? other.getCandidateName() == null : this.getCandidateName().equals(other.getCandidateName()))
                && (this.getVoteRound() == null ? other.getVoteRound() == null : this.getVoteRound().equals(other.getVoteRound()))
                && (this.getVoteStage() == null ? other.getVoteStage() == null : this.getVoteStage().equals(other.getVoteStage()))
                && (this.getVoterAddress() == null ? other.getVoterAddress() == null : this.getVoterAddress().equals(other.getVoterAddress()))
                && (this.getSnapBlockNumber() == null ? other.getSnapBlockNumber() == null : this.getSnapBlockNumber().equals(other.getSnapBlockNumber()))
                && (this.getSnapBlockTimestamp() == null ? other.getSnapBlockTimestamp() == null : this.getSnapBlockTimestamp().equals(other.getSnapBlockTimestamp()))
                && (this.getVoteTotalAmount() == null ? other.getVoteTotalAmount() == null : this.getVoteTotalAmount().equals(other.getVoteTotalAmount()))
                && (this.getCreateTimestamp() == null ? other.getCreateTimestamp() == null : this.getCreateTimestamp().equals(other.getCreateTimestamp()))
                && (this.getUpdateTimestamp() == null ? other.getUpdateTimestamp() == null : this.getUpdateTimestamp().equals(other.getUpdateTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_node_vote_record_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCandidateAddress() == null) ? 0 : getCandidateAddress().hashCode());
        result = prime * result + ((getCandidateName() == null) ? 0 : getCandidateName().hashCode());
        result = prime * result + ((getVoteRound() == null) ? 0 : getVoteRound().hashCode());
        result = prime * result + ((getVoteStage() == null) ? 0 : getVoteStage().hashCode());
        result = prime * result + ((getVoterAddress() == null) ? 0 : getVoterAddress().hashCode());
        result = prime * result + ((getSnapBlockNumber() == null) ? 0 : getSnapBlockNumber().hashCode());
        result = prime * result + ((getSnapBlockTimestamp() == null) ? 0 : getSnapBlockTimestamp().hashCode());
        result = prime * result + ((getVoteTotalAmount() == null) ? 0 : getVoteTotalAmount().hashCode());
        result = prime * result + ((getCreateTimestamp() == null) ? 0 : getCreateTimestamp().hashCode());
        result = prime * result + ((getUpdateTimestamp() == null) ? 0 : getUpdateTimestamp().hashCode());
        return result;
    }
}