package com.hpb.bc.entity;

import java.util.Date;

public class StatTransactionAmountDaily extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_transaction_amount_daily.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_transaction_amount_daily.transaction_amount
     *
     * @mbg.generated
     */
    private Long transactionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_transaction_amount_daily.transaction_date
     *
     * @mbg.generated
     */
    private Date transactionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_transaction_amount_daily.create_timestamp
     *
     * @mbg.generated
     */
    private Date createTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_transaction_amount_daily.id
     *
     * @return the value of stat_transaction_amount_daily.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_transaction_amount_daily.id
     *
     * @param id the value for stat_transaction_amount_daily.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_transaction_amount_daily.transaction_amount
     *
     * @return the value of stat_transaction_amount_daily.transaction_amount
     * @mbg.generated
     */
    public Long getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_transaction_amount_daily.transaction_amount
     *
     * @param transactionAmount the value for stat_transaction_amount_daily.transaction_amount
     * @mbg.generated
     */
    public void setTransactionAmount(Long transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_transaction_amount_daily.transaction_date
     *
     * @return the value of stat_transaction_amount_daily.transaction_date
     * @mbg.generated
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_transaction_amount_daily.transaction_date
     *
     * @param transactionDate the value for stat_transaction_amount_daily.transaction_date
     * @mbg.generated
     */
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_transaction_amount_daily.create_timestamp
     *
     * @return the value of stat_transaction_amount_daily.create_timestamp
     * @mbg.generated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_transaction_amount_daily.create_timestamp
     *
     * @param createTimestamp the value for stat_transaction_amount_daily.create_timestamp
     * @mbg.generated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_transaction_amount_daily
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StatTransactionAmountDaily other = (StatTransactionAmountDaily) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getTransactionAmount() == null ? other.getTransactionAmount() == null : this.getTransactionAmount().equals(other.getTransactionAmount()))
                && (this.getTransactionDate() == null ? other.getTransactionDate() == null : this.getTransactionDate().equals(other.getTransactionDate()))
                && (this.getCreateTimestamp() == null ? other.getCreateTimestamp() == null : this.getCreateTimestamp().equals(other.getCreateTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_transaction_amount_daily
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTransactionAmount() == null) ? 0 : getTransactionAmount().hashCode());
        result = prime * result + ((getTransactionDate() == null) ? 0 : getTransactionDate().hashCode());
        result = prime * result + ((getCreateTimestamp() == null) ? 0 : getCreateTimestamp().hashCode());
        return result;
    }
}